// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1PlBoKy2QJ90f0aaoTZgYWCz3RTXAnI',
    appId: '1:1020905258385:web:eda8903e83d11ec86eae30',
    messagingSenderId: '1020905258385',
    projectId: 'sharecare-67998',
    authDomain: 'sharecare-67998.firebaseapp.com',
    storageBucket: 'sharecare-67998.appspot.com',
    measurementId: 'G-9627E3C27B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqsyoQD3Q2AI33cWtqZHzNgywdT41t1e0',
    appId: '1:1020905258385:android:f6c7af89b890569f6eae30',
    messagingSenderId: '1020905258385',
    projectId: 'sharecare-67998',
    storageBucket: 'sharecare-67998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9o6IqGDogfEi3wuCm6sAGmrMM9kqkwf4',
    appId: '1:1020905258385:ios:0540d1543773a6056eae30',
    messagingSenderId: '1020905258385',
    projectId: 'sharecare-67998',
    storageBucket: 'sharecare-67998.appspot.com',
    iosClientId: '1020905258385-jntart62337tfb43d86di3jkkhhpdtbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nileeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm1PlBoKy2QJ90f0aaoTZgYWCz3RTXAnI',
    appId: '1:1020905258385:web:efb12de53cfd56d26eae30',
    messagingSenderId: '1020905258385',
    projectId: 'sharecare-67998',
    authDomain: 'sharecare-67998.firebaseapp.com',
    storageBucket: 'sharecare-67998.appspot.com',
    measurementId: 'G-J14ZSM202E',
  );
}
